### ISSUE TITLE
Can't press "done" 

### ISSUE THREAD

**Issue by ecamach13** [BIDMCDigitalPsychiatry/DOORS#85]
We've had trouble accessing the "done" feature on the phones of participants. I've attached a video of this here. The problem exists for androids and iphones, both newer versions and old. I have attached only one example, the others were too large of files to upload, but this issue is ongoing.

https://user-images.githubusercontent.com/70787908/116094106-3ecdef00-a675-11eb-85e7-27d937a9636e.MOV

**Comment by ecamach13** [comment]
https://user-images.githubusercontent.com/70787908/116094532-9f5d2c00-a675-11eb-931e-cd602e0e5b79.mov

**Comment by cvanem** [comment]
@ecamach13  The video's look like a scrolling issue for small screen sizes.  I will take a look.

**Comment by cvanem** [comment]
For some reason, the page height calculation appears to not be working correctly on physical mobile devices.  I was unable to reproduce the issue in the development environment.

A fix was pushed, which adds a bottom margin to the Page component.  This was verified as a working fix in the production environment.
